### ISSUE TITLE
Can search above 20 for App_limit

### ISSUE THREAD

**Issue by rcmpayne** [nshuba/download_apks#1]
app_limit = 10000
app_limit = 100
app_limit = 1000

results is 20 for each category

**Comment by nshuba** [comment]
Thanks for reporting this! I fixed it for 100 apps or so.

Note that there is a Google Play limit for too many requests. I was able to successfully fetch 100 apps, but testing with 1k got me "'Too many results requested.'" You can see more about this issue here: https://github.com/NoMore201/googleplay-api/issues/43
